-- Allow bulk COPY / explicit id loads (e.g. cloning PROD->DEV) by changing
-- IDENTITY columns from GENERATED ALWAYS to GENERATED BY DEFAULT.
--
-- This does NOT affect generated (computed) columns like tsv_en/url_hash/post_key.

ALTER TABLE taxonomy.vaccine_term
  ALTER COLUMN id SET GENERATED BY DEFAULT;

ALTER TABLE podcasts.shows
  ALTER COLUMN id SET GENERATED BY DEFAULT;
