BEGIN;

-- ------------------------------------------------------------
-- 1. Ensure youtube schema exists
-- ------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS youtube;

-- ------------------------------------------------------------
-- 2. Move podcast trigger function into podcasts schema
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION podcasts.trg_episode_reg_del() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM sm.post_registry
   WHERE platform = 'podcast_episode'
     AND key1 = OLD.id::text
     AND key2 IS NULL;
  RETURN OLD;
END $$;

DROP TRIGGER IF EXISTS ep_reg_del ON podcasts.episodes;
DROP FUNCTION IF EXISTS sm.trg_ep_reg_del();

CREATE TRIGGER ep_reg_del
AFTER DELETE ON podcasts.episodes
FOR EACH ROW
EXECUTE FUNCTION podcasts.trg_episode_reg_del();

-- ------------------------------------------------------------
-- 3. Drop youtube triggers before moving tables
-- ------------------------------------------------------------
DROP TRIGGER IF EXISTS yv_reg_del ON sm.youtube_video;
DROP TRIGGER IF EXISTS yc_reg_ins ON sm.youtube_comment;
DROP TRIGGER IF EXISTS yc_reg_del ON sm.youtube_comment;

-- ------------------------------------------------------------
-- 4. Move youtube_video → youtube.video
-- ------------------------------------------------------------
ALTER TABLE sm.youtube_video SET SCHEMA youtube;
ALTER TABLE youtube.youtube_video RENAME TO video;

ALTER TABLE youtube.video
    RENAME CONSTRAINT youtube_video_pkey TO video_pkey;

-- ------------------------------------------------------------
-- 5. Move youtube_comment → youtube.comment
-- ------------------------------------------------------------
ALTER TABLE sm.youtube_comment SET SCHEMA youtube;
ALTER TABLE youtube.youtube_comment RENAME TO comment;

ALTER TABLE youtube.comment
    RENAME CONSTRAINT youtube_comment_pkey TO comment_pkey;

-- ------------------------------------------------------------
-- 6. Fix foreign key to new youtube.video table
-- ------------------------------------------------------------
ALTER TABLE youtube.comment
    DROP CONSTRAINT youtube_comment_video_fk;

ALTER TABLE youtube.comment
    ADD CONSTRAINT comment_video_fk
    FOREIGN KEY (video_id)
    REFERENCES youtube.video(video_id)
    ON DELETE CASCADE;

-- ------------------------------------------------------------
-- 7. Move youtube trigger functions into youtube schema
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION youtube.trg_video_reg_del() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM sm.post_registry
   WHERE platform = 'youtube_video'
     AND key1 = OLD.video_id
     AND key2 IS NULL;
  RETURN OLD;
END $$;

CREATE OR REPLACE FUNCTION youtube.trg_comment_reg_ins() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO sm.post_registry(platform, key1, key2)
  VALUES ('youtube_comment', NEW.video_id, NEW.comment_id)
  ON CONFLICT (platform, key1, key2) DO NOTHING;
  RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION youtube.trg_comment_reg_del() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM sm.post_registry
   WHERE platform = 'youtube_comment'
     AND key1 = OLD.video_id
     AND key2 = OLD.comment_id;
  RETURN OLD;
END $$;

DROP FUNCTION IF EXISTS sm.trg_yv_reg_del();
DROP FUNCTION IF EXISTS sm.trg_yc_reg_ins();
DROP FUNCTION IF EXISTS sm.trg_yc_reg_del();

-- ------------------------------------------------------------
-- 8. Recreate youtube triggers on new tables
-- ------------------------------------------------------------
CREATE TRIGGER yv_reg_del
AFTER DELETE ON youtube.video
FOR EACH ROW
EXECUTE FUNCTION youtube.trg_video_reg_del();

CREATE TRIGGER yc_reg_ins
AFTER INSERT ON youtube.comment
FOR EACH ROW
EXECUTE FUNCTION youtube.trg_comment_reg_ins();

CREATE TRIGGER yc_reg_del
AFTER DELETE ON youtube.comment
FOR EACH ROW
EXECUTE FUNCTION youtube.trg_comment_reg_del();

-- ------------------------------------------------------------
-- 9. Create youtube.transcript_segments
-- ------------------------------------------------------------
CREATE TABLE youtube.transcript_segments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id text NOT NULL,
    seg_idx integer NOT NULL,
    start_s numeric NOT NULL,
    end_s numeric NOT NULL,
    text text,
    date_entered timestamp with time zone DEFAULT now() NOT NULL,
    tsv_en tsvector GENERATED ALWAYS AS (
        to_tsvector('english', COALESCE(text, ''))
    ) STORED,
    CONSTRAINT yt_transcript_segments_time_chk
        CHECK (end_s >= start_s),
    CONSTRAINT yt_transcript_segments_video_fk
        FOREIGN KEY (video_id)
        REFERENCES youtube.video(video_id)
        ON DELETE CASCADE
);

CREATE INDEX yt_transcript_segments_tsv_en_gin
    ON youtube.transcript_segments USING GIN (tsv_en);

CREATE INDEX yt_transcript_segments_video_idx
    ON youtube.transcript_segments (video_id);

-- ------------------------------------------------------------
-- 10. Update sm.posts_all view
-- ------------------------------------------------------------
CREATE OR REPLACE VIEW sm.posts_all AS
    -- (unchanged UNION branches omitted for brevity)
    SELECT pr.id AS post_id,
           pr.platform,
           pr.key1,
           pr.key2,
           yv.date_entered,
           yv.created_at_ts,
           yv.transcript AS text,
           yv.tsv_en,
           yv.is_en,
           yv.view_count AS primary_metric,
           yv.url
    FROM sm.post_registry pr
    JOIN youtube.video yv
      ON pr.platform = 'youtube_video'
     AND pr.key1 = yv.video_id
     AND pr.key2 IS NULL
UNION ALL
    SELECT pr.id AS post_id,
           pr.platform,
           pr.key1,
           pr.key2,
           yc.date_entered,
           yc.created_at_ts,
           yc.filtered_text AS text,
           yc.tsv_en,
           yc.is_en,
           yc.like_count AS primary_metric,
           yc.comment_url AS url
    FROM sm.post_registry pr
    JOIN youtube.comment yc
      ON pr.platform = 'youtube_comment'
     AND pr.key1 = yc.video_id
     AND pr.key2 = yc.comment_id;

-- ------------------------------------------------------------
-- 11. Add duration_seconds column + trigger
-- ------------------------------------------------------------

-- 1. Add a normal column
ALTER TABLE youtube.video
ADD COLUMN duration_seconds integer;

-- 2. Create trigger function
CREATE OR REPLACE FUNCTION youtube.set_duration_seconds()
RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.duration_iso IS NOT NULL THEN
        NEW.duration_seconds :=
            EXTRACT(EPOCH FROM NEW.duration_iso::interval)::integer;
    ELSE
        NEW.duration_seconds := NULL;
    END IF;
    RETURN NEW;
END $$;

-- 3. Attach trigger
CREATE TRIGGER yt_video_duration_seconds_trg
BEFORE INSERT OR UPDATE OF duration_iso
ON youtube.video
FOR EACH ROW
EXECUTE FUNCTION youtube.set_duration_seconds();

-- 4. Backfill existing rows
UPDATE youtube.video
SET duration_iso = duration_iso;

-- 5. Index
CREATE INDEX youtube_video_duration_seconds_idx
    ON youtube.video (duration_seconds);

