-- 1) Add parent_comment_id column (nullable)
ALTER TABLE youtube.comment
ADD COLUMN parent_comment_id text;

-- 2) Ensure comment_id is NOT NULL (required for PK)
ALTER TABLE youtube.comment
ALTER COLUMN comment_id SET NOT NULL;

-- 3) Add self-referential foreign key for replies
ALTER TABLE youtube.comment
ADD CONSTRAINT youtube_comment_parent_fk
FOREIGN KEY (video_id, parent_comment_id)
REFERENCES youtube.comment(video_id, comment_id)
ON DELETE CASCADE;

-- 4) Add search term subset table
CREATE TABLE taxonomy.vaccine_term_subset (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    description text,
    date_entered timestamp with time zone DEFAULT now() NOT NULL
);

-- 5) Add member items ofr vaccine subset
CREATE TABLE taxonomy.vaccine_term_subset_member (
    subset_id integer NOT NULL,
    term_id integer NOT NULL,
    date_entered timestamp with time zone DEFAULT now() NOT NULL,

    PRIMARY KEY (subset_id, term_id),

    CONSTRAINT vaccine_term_subset_member_subset_fk
        FOREIGN KEY (subset_id)
        REFERENCES taxonomy.vaccine_term_subset(id)
        ON DELETE CASCADE,

    CONSTRAINT vaccine_term_subset_member_term_fk
        FOREIGN KEY (term_id)
        REFERENCES taxonomy.vaccine_term(id)
        ON DELETE CASCADE
);

-- 6) Add youtube search status table

CREATE TABLE youtube.search_status (
    term_id integer PRIMARY KEY,
    last_found_ts timestamptz NOT NULL,
    date_entered timestamptz DEFAULT now() NOT NULL,
    last_updated timestamptz DEFAULT now() NOT NULL,

    CONSTRAINT youtube_search_status_term_fk
        FOREIGN KEY (term_id)
        REFERENCES taxonomy.vaccine_term(id)
        ON DELETE CASCADE
);

CREATE INDEX youtube_search_status_last_found_idx
ON youtube.search_status (last_found_ts);
