[service]
description = "transcribes youtube videos (is_en labeled after transcript by label_en)"
type = "oneshot"
runtime = "transcription"


[timer]
on_boot_sec = "2min"
on_unit_inactive_sec = "2min"
persistent = false 
